name: Get version information task

on:
  workflow_call:
    outputs:
      # Version information outputs
      SemVer2:
        value: ${{ jobs.get-version.outputs.SemVer2 }}
      AssemblyVersion:
        value: ${{ jobs.get-version.outputs.AssemblyVersion }}
      AssemblyFileVersion:
        value: ${{ jobs.get-version.outputs.AssemblyFileVersion }}
      AssemblyInformationalVersion:
        value: ${{ jobs.get-version.outputs.AssemblyInformationalVersion }}

jobs:

  get-version:
    name: Get version information job
    runs-on: ubuntu-latest
    outputs:
      SemVer2: ${{ steps.nbgv.outputs.SemVer2 }}
      AssemblyVersion: ${{ steps.nbgv.outputs.AssemblyVersion }}
      AssemblyFileVersion: ${{ steps.nbgv.outputs.AssemblyFileVersion }}
      AssemblyInformationalVersion: ${{ steps.nbgv.outputs.AssemblyInformationalVersion }}

    steps:

      - name: Setup .NET SDK step
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Checkout code step
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run Nerdbank.GitVersioning tool step
        id: nbgv
        uses: dotnet/nbgv@master
